### ISSUE TITLE
[Web]문제 제출 시 해당 문제로 페이지 이동

### ISSUE THREAD

**Issue by rrrmaster** [codeboxorg/codestack-web#36]

**Comment by je0ngyun** [comment]
완료했습니다~
- 문제 제출 완료 시 "결과 확인하기" 버튼 표출
- "결과 확인하기" 버튼 클릭시 문제 제출 결과 상세 페이지 이동
- 문제 제출 결과 상세페이지는 퍼블리싱이 되지않은 VAC Debugger만 적용해놓은 페이지라 작업 필요
